# Generated by Django 5.1.3 on 2024-11-25 04:30

import authentication.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_profile_birthday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(default=authentication.models.default_profile_picture, max_length=255, upload_to='profile_pictures/'),
        ),
    ]
