# Generated by Django 5.1.3 on 2024-12-02 22:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_profile_profile_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(max_length=1000)),
                ('image', models.ImageField(upload_to='post_pics/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('size', models.CharField(blank=True, max_length=50, null=True)),
                ('size_exactness', models.CharField(blank=True, choices=[('exact', 'Exact'), ('approximate', 'Approximate')], max_length=20, null=True)),
                ('colour', models.CharField(blank=True, choices=[('red', 'Red'), ('blue', 'Blue'), ('green', 'Green'), ('yellow', 'Yellow'), ('black', 'Black'), ('white', 'White'), ('brown', 'Brown'), ('grey', 'Grey'), ('other', 'Other')], max_length=20, null=True)),
                ('custom_colour', models.CharField(blank=True, max_length=50, null=True)),
                ('shape', models.CharField(blank=True, choices=[('round', 'Round'), ('square', 'Square'), ('rectangular', 'Rectangular'), ('triangular', 'Triangular'), ('oval', 'Oval'), ('irregular', 'Irregular'), ('other', 'Other')], max_length=20, null=True)),
                ('custom_shape', models.CharField(blank=True, max_length=300, null=True)),
                ('weight', models.CharField(blank=True, max_length=50, null=True)),
                ('weight_exactness', models.CharField(blank=True, choices=[('exact', 'Exact'), ('approximate', 'Approximate')], max_length=20, null=True)),
                ('texture', models.CharField(blank=True, max_length=300, null=True)),
                ('origin', models.CharField(blank=True, max_length=300, null=True)),
                ('value', models.CharField(blank=True, max_length=50, null=True)),
                ('condition', models.CharField(blank=True, choices=[('new', 'New'), ('like_new', 'Like New'), ('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor'), ('other', 'Other')], max_length=20, null=True)),
                ('custom_condition', models.CharField(blank=True, max_length=100, null=True)),
                ('smell', models.CharField(blank=True, max_length=300, null=True)),
                ('taste', models.CharField(blank=True, max_length=300, null=True)),
                ('origin_of_acquisition', models.CharField(blank=True, max_length=300, null=True)),
                ('pattern', models.CharField(blank=True, max_length=300, null=True)),
                ('functionality', models.CharField(blank=True, max_length=300, null=True)),
                ('other_multimedia', models.ImageField(blank=True, null=True, upload_to='post_other_images/')),
                ('status', models.CharField(choices=[('unknown', 'Unknown'), ('solved', 'Solved')], default='unknown', max_length=20)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WikidataTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_type', models.CharField(choices=[('images', 'Images'), ('icons', 'Icons'), ('markings', 'Markings'), ('print', 'Print'), ('brand', 'Brand'), ('time_period', 'Time Period'), ('object_domain', 'Object Domain'), ('other', 'Other')], max_length=20)),
                ('wikidata_id', models.CharField(max_length=20)),
                ('label', models.CharField(max_length=100)),
                ('link', models.CharField(blank=True, max_length=300, null=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wikidata_tags', to='core.post')),
            ],
        ),
    ]
