# Generated by Django 5.1.3 on 2024-12-10 02:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_post_wikidatatag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wikidatatag',
            name='tag_type',
        ),
    ]
