# Generated by Django 5.1.3 on 2024-12-10 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_wikidatatag_tag_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='brand',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='custom_elasticity',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='custom_hardness',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='custom_material',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='custom_object_domain',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='custom_time_period',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='custom_transparency',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='elasticity',
            field=models.CharField(blank=True, choices=[('elastic', 'Elastic'), ('non_elastic', 'Non-elastic'), ('semi_elastic', 'Semi-elastic'), ('other', 'Other')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='hardness',
            field=models.CharField(blank=True, choices=[('soft', 'Soft'), ('medium', 'Medium'), ('hard', 'Hard'), ('other', 'Other')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='icon_description',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='image_description',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='markings',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='material',
            field=models.CharField(blank=True, choices=[('metal', 'Metal'), ('wood', 'Wood'), ('plastic', 'Plastic'), ('glass', 'Glass'), ('fabric', 'Fabric'), ('ceramic', 'Ceramic'), ('other', 'Other')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='object_domain',
            field=models.CharField(blank=True, choices=[('art_design', 'Art and Design'), ('technology', 'Technology'), ('household', 'Household'), ('fashion_accessories', 'Fashion and Accessories'), ('tools_equipment', 'Tools and Equipment'), ('toys_games', 'Toys and Games'), ('historical_cultural', 'Historical and Cultural'), ('other', 'Other')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='print_description',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='time_period',
            field=models.CharField(blank=True, choices=[('ancient', 'Ancient'), ('medieval', 'Medieval'), ('modern', 'Modern'), ('contemporary', 'Contemporary'), ('other', 'Other')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='transparency',
            field=models.CharField(blank=True, choices=[('transparent', 'Transparent'), ('translucent', 'Translucent'), ('opaque', 'Opaque'), ('other', 'Other')], max_length=20, null=True),
        ),
    ]
