# Generated by Django 5.1.3 on 2024-12-10 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_post_brand_post_custom_elasticity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='approximate_size',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='approximate_weight',
            field=models.CharField(blank=True, choices=[('lightweight', 'Lightweight'), ('medium', 'Medium Weight'), ('heavy', 'Heavy'), ('other', 'Other')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='custom_approximate_weight',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='custom_functionality',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='custom_pattern',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='custom_smell',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='custom_taste',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='custom_texture',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='depth',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='exact_weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='height',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='size_type',
            field=models.CharField(blank=True, choices=[('exact', 'Exact'), ('approximate', 'Approximate')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='size_unit',
            field=models.CharField(blank=True, choices=[('mm', 'Millimeter'), ('cm', 'Centimeter'), ('m', 'Meter'), ('km', 'Kilometer'), ('in', 'Inch'), ('ft', 'Foot'), ('yd', 'Yard'), ('mi', 'Mile')], max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='weight_type',
            field=models.CharField(blank=True, choices=[('exact', 'Exact'), ('approximate', 'Approximate')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='weight_unit',
            field=models.CharField(blank=True, choices=[('mg', 'Milligram'), ('g', 'Gram'), ('kg', 'Kilogram'), ('t', 'Ton'), ('oz', 'Ounce'), ('lb', 'Pound'), ('st', 'Stone')], max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='width',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='functionality',
            field=models.CharField(blank=True, choices=[('rigid', 'Rigid'), ('moving', 'Moving'), ('adhesive', 'Adhesive'), ('other', 'Other')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='pattern',
            field=models.CharField(blank=True, choices=[('plain', 'Plain'), ('patterned', 'Patterned'), ('striped', 'Striped'), ('checkered', 'Checkered'), ('marbled', 'Marbled'), ('other', 'Other')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='smell',
            field=models.CharField(blank=True, choices=[('odorless', 'Odorless'), ('chemical', 'Chemical'), ('earthy', 'Earthy'), ('metallic', 'Metallic'), ('fragrant', 'Fragrant'), ('other', 'Other')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='taste',
            field=models.CharField(blank=True, choices=[('sweet', 'Sweet'), ('salty', 'Salty'), ('metallic', 'Metallic'), ('bitter', 'Bitter'), ('sour', 'Sour'), ('other', 'Other')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='texture',
            field=models.CharField(blank=True, choices=[('smooth', 'Smooth'), ('rough', 'Rough'), ('grainy', 'Grainy'), ('polished', 'Polished'), ('matte', 'Matte'), ('other', 'Other')], max_length=20, null=True),
        ),
    ]
