# Generated by Django 5.1.3 on 2024-12-10 03:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_post_approximate_size_post_approximate_weight_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('value', models.TextField()),
                ('instance_id', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='core.post')),
            ],
            options={
                'ordering': ['name', 'instance_id'],
            },
        ),
    ]
