# Generated by Django 5.1.3 on 2024-12-15 15:34

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_profile_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.get_unique_post_path),
        ),
        migrations.AlterField(
            model_name='postmultimedia',
            name='file',
            field=models.FileField(upload_to=core.models.get_unique_multimedia_path),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.get_unique_profile_path),
        ),
    ]
